server:
  port: 8761

spring:
  application:
    name: eureka01

eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/